version: 2
updates:
  - package-ecosystem: cargo
    directory: /gui/src-tauri
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(gui)"

  - package-ecosystem: cargo
    directory: /launcher/src-tauri
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(launcher)"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(ci)"
