//! Phase 6: proves the privileged phase now runs `core::install`'s real
//! plans, not Phase 4's `println!`-only placeholders - end to end, through
//! the same single-`pkexec` mechanism `tests/single_pkexec_call.rs`
//! already validated, with real progress streaming.
//!
//! Unlike that file's fake `pkexec` (which only logs its invocation and
//! exits, to count calls cheaply), this one actually `exec`s its
//! arguments - truly re-invoking this same compiled binary with
//! `--run-privileged-phase`, so the real `steps/{ollama,gpu,webui}.rs`
//! code runs for real. Every *external* tool that code would otherwise
//! shell out to (`lspci`, `rocminfo`, `ollama`, `systemctl`, `curl`,
//! `pacman`, `pipx`) is faked too, via a `PATH` containing only these
//! fakes plus the real `env`/`bash`/`sh` needed for shebangs - so this
//! test needs no real root, never touches the real system, and completes
//! in well under a second (a fake `curl` answers "ready" on the very
//! first poll, rather than a real 30-attempt/1s-apart wait).
//!
//! Scenario: Arch (`pacman`), AMD GPU with an RDNA4 chip needing the HSA
//! override, Ollama already on `PATH` (skips the `curl|sh` install), pipx
//! already present (skips `webui-deps`'s package install - that path is
//! covered by `exec.rs`'s own `pkg_install_commands` unit tests instead,
//! to keep this one scenario manageable).

use selfllama_installer::privileged::{spawn_privileged_phase, PhaseLine, PrivilegedPhaseOptions};
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

struct Fixture {
    tmp: PathBuf,
    fake_bin: PathBuf,
    pkexec_log: PathBuf,
    pacman_log: PathBuf,
    os_release: PathBuf,
    rocm_opt_dir: PathBuf,
    override_path: PathBuf,
}

fn write_script(path: &Path, body: &str) {
    fs::write(path, format!("#!/usr/bin/env bash\n{body}\n")).unwrap();
    let mut perms = fs::metadata(path).unwrap().permissions();
    perms.set_mode(0o755);
    fs::set_permissions(path, perms).unwrap();
}

fn build_fixture(name: &str) -> Fixture {
    let tmp = std::env::temp_dir().join(format!("selfllama-e2e-{name}-{}", std::process::id()));
    fs::create_dir_all(&tmp).unwrap();
    let fake_bin = tmp.join("bin");
    fs::create_dir_all(&fake_bin).unwrap();
    let rocm_opt_dir = tmp.join("opt-empty");
    fs::create_dir_all(&rocm_opt_dir).unwrap();

    let pkexec_log = tmp.join("pkexec-calls.log");
    let pacman_log = tmp.join("pacman-calls.log");
    let os_release = tmp.join("os-release");
    fs::write(&os_release, "ID=arch\nPRETTY_NAME=\"Arch Linux\"\n").unwrap();
    let override_path = tmp.join("override.conf");

    // Re-execs its arguments for real (unlike single_pkexec_call.rs's
    // count-only fake), after logging them the same way, so both "one
    // call" and "the real worker ran" can be checked from the same file.
    write_script(
        &fake_bin.join("pkexec"),
        &format!("echo \"$*\" >> '{}'\nexec \"$@\"", pkexec_log.display()),
    );
    write_script(&fake_bin.join("lspci"), "echo '03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 48 [Radeon RX 9070 XT] [1002:7550] (rev c0)'");
    write_script(&fake_bin.join("rocminfo"), "echo '  Name: gfx1201'");
    write_script(&fake_bin.join("ollama"), "exit 0");
    write_script(&fake_bin.join("systemctl"), "exit 0");
    write_script(&fake_bin.join("curl"), "exit 0");
    write_script(&fake_bin.join("pipx"), "exit 0");
    write_script(
        &fake_bin.join("pacman"),
        &format!("echo \"$*\" >> '{}'\nexit 0", pacman_log.display()),
    );

    Fixture { tmp, fake_bin, pkexec_log, pacman_log, os_release, rocm_opt_dir, override_path }
}

impl Fixture {
    fn path_value(&self) -> String {
        // Fakes first, then the real system dirs - needed for `env`/
        // `bash` (every fake's own shebang) to resolve, not to find a
        // real lspci/rocminfo/pacman/etc, which the fakes above already
        // shadow.
        format!("{}:/usr/bin:/bin", self.fake_bin.display())
    }
}

/// The real `selfllama-installer` `[[bin]]`, not this test's own binary -
/// needed since the fake `pkexec` here really `exec`s its argument.
/// `std::env::current_exe()` inside an integration test returns the test
/// binary's own path (`.../target/debug/deps/real_plans_end_to_end-<hash>`,
/// the harness generated by `#[test]`, which has no
/// `--run-privileged-phase` handling of its own) - `cargo test` builds
/// every target in the package first, including the `[[bin]]`, which ends
/// up as a sibling of `deps/`.
fn installer_binary_path() -> PathBuf {
    let test_exe = std::env::current_exe().expect("current_exe");
    let deps_dir = test_exe.parent().expect("deps dir");
    let target_debug = deps_dir.parent().expect("target/debug dir");
    let candidate = target_debug.join("selfllama-installer");
    assert!(
        candidate.is_file(),
        "expected the selfllama-installer binary at {} (built alongside this test binary by `cargo test`)",
        candidate.display()
    );
    candidate
}

#[test]
fn privileged_phase_runs_core_installs_real_plans_end_to_end() {
    let fx = build_fixture("main");
    let path = fx.path_value();
    let os_release = fx.os_release.to_string_lossy().into_owned();
    let rocm_opt_dir = fx.rocm_opt_dir.to_string_lossy().into_owned();
    let override_path = fx.override_path.to_string_lossy().into_owned();

    let current_exe = installer_binary_path();
    let handle = spawn_privileged_phase(
        &current_exe,
        PrivilegedPhaseOptions::default(),
        Some(&path),
        &[
            ("OS_RELEASE_FILE", &os_release),
            ("ROCM_OPT_DIR", &rocm_opt_dir),
            ("OLLAMA_SERVICE_OVERRIDE_PATH", &override_path),
        ],
    )
    .expect("failed to spawn the privileged phase");

    let lines: Vec<String> = handle
        .lines
        .iter()
        .map(|line| match line {
            PhaseLine::Stdout(s) | PhaseLine::Stderr(s) => s,
        })
        .collect();
    let status = handle.wait();

    let pkexec_calls = fs::read_to_string(&fx.pkexec_log).unwrap_or_default();
    let pacman_calls = fs::read_to_string(&fx.pacman_log).unwrap_or_default();
    let override_content = fs::read_to_string(&fx.override_path).unwrap_or_default();
    fs::remove_dir_all(&fx.tmp).ok();

    assert_eq!(status, Ok(()), "full log:\n{}", lines.join("\n"));

    // Still exactly one pkexec call for the whole phase, as established in
    // Phase 4 - unaffected by wiring in real steps.
    assert_eq!(pkexec_calls.lines().count(), 1);
    assert_eq!(pkexec_calls.trim(), format!("{} --run-privileged-phase", current_exe.display()));

    // The real point of this test: core::install::gpu::amd_plan's exact
    // Arch package list was really passed to a real pacman invocation -
    // not a placeholder string, the actual plan data from Phase 5.
    assert_eq!(
        pacman_calls.trim(),
        "-Sy --noconfirm --needed vulkan-radeon vulkan-icd-loader vulkan-tools rocminfo"
    );

    // And the gfx1201-needs-an-override branch really wrote the exact
    // content core::install::gpu/mod.rs's render_ollama_vulkan_dropin
    // produces for that case.
    assert_eq!(
        override_content,
        "[Service]\nEnvironment=\"OLLAMA_VULKAN=1\"\nEnvironment=\"HSA_OVERRIDE_GFX_VERSION=11.5.0\"\n"
    );

    // Streaming end to end, with real plan-derived output, not just Phase
    // 4's two canned lines: every step reached "done", and the real
    // per-step log lines (not the stub's "(stub) would...") came through.
    let joined = lines.join("\n");
    assert!(joined.contains(r#""id":"ollama","label":"Installing Ollama","status":"running""#));
    assert!(joined.contains(r#""id":"ollama","label":"Installing Ollama","status":"done""#));
    assert!(joined.contains(r#""id":"gpu","label":"Configuring GPU","status":"done""#));
    assert!(joined.contains(r#""id":"webui-deps","label":"Installing Open WebUI prerequisites","status":"done""#));
    assert!(joined.contains("Ollama already installed."));
    assert!(joined.contains("Ollama is ready at http://127.0.0.1:11434"));
    assert!(joined.contains("GPU selected for acceleration:") && joined.contains("(amd)"));
    assert!(joined.contains("AMD chip identified: gfx1201"));
    assert!(joined.contains("pipx already present, nothing to install."));
    assert!(joined.contains("GPU configuration complete."));
    assert!(!joined.contains("(stub)"), "no placeholder output should remain:\n{joined}");
}

#[test]
fn nvidia_without_a_driver_stops_the_sequence_with_needs_confirmation_not_a_silent_install() {
    let fx = build_fixture("nvidia");
    // Same Arch os-release, but lspci now reports an Nvidia card with no
    // nvidia-smi anywhere on the fake PATH (driver "absent").
    write_script(&fx.fake_bin.join("lspci"), "echo '01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU104 [GeForce RTX 2080] [10de:1e87] (rev a1)'");
    fs::remove_file(fx.fake_bin.join("rocminfo")).ok();

    let path = fx.path_value();
    let os_release = fx.os_release.to_string_lossy().into_owned();
    let rocm_opt_dir = fx.rocm_opt_dir.to_string_lossy().into_owned();
    let override_path = fx.override_path.to_string_lossy().into_owned();

    let current_exe = installer_binary_path();
    let handle = spawn_privileged_phase(
        &current_exe,
        PrivilegedPhaseOptions::default(),
        Some(&path),
        &[
            ("OS_RELEASE_FILE", &os_release),
            ("ROCM_OPT_DIR", &rocm_opt_dir),
            ("OLLAMA_SERVICE_OVERRIDE_PATH", &override_path),
        ],
    )
    .unwrap();

    let lines: Vec<String> = handle
        .lines
        .iter()
        .map(|line| match line {
            PhaseLine::Stdout(s) | PhaseLine::Stderr(s) => s,
        })
        .collect();
    let status = handle.wait();
    let pacman_calls = fs::read_to_string(&fx.pacman_log).unwrap_or_default();
    fs::remove_dir_all(&fx.tmp).ok();

    // The sequence stops (a non-zero exit, same observable shape as a real
    // failure) rather than either silently installing the driver or
    // silently skipping the GPU step and moving on.
    assert_eq!(status, Err("privileged phase exited with exit status: 1".to_string()));

    let joined = lines.join("\n");
    assert!(joined.contains(r#""id":"gpu","label":"Configuring GPU","status":"needsconfirmation""#), "{joined}");
    assert!(joined.contains("Nvidia driver"));
    assert!(joined.contains("Install the Nvidia driver now?"));
    assert!(joined.contains("nvidia-utils") || joined.contains("nvidia,"), "{joined}");
    // webui-deps must never run: the sequence stopped at gpu.
    assert!(!joined.contains(r#""id":"webui-deps""#), "{joined}");
    // And no package was ever installed without a confirmed decision.
    assert!(pacman_calls.is_empty(), "must not install a driver without confirmation: {pacman_calls}");
}

#[test]
fn nvidia_confirmed_on_a_second_call_actually_installs_the_driver() {
    // Same scenario as above, but this is the second call gui/ would make
    // after a real user really clicked "yes" - PrivilegedPhaseOptions'
    // confirm_nvidia_driver_install is now true.
    let fx = build_fixture("nvidia-confirmed");
    write_script(&fx.fake_bin.join("lspci"), "echo '01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU104 [GeForce RTX 2080] [10de:1e87] (rev a1)'");
    fs::remove_file(fx.fake_bin.join("rocminfo")).ok();

    let path = fx.path_value();
    let os_release = fx.os_release.to_string_lossy().into_owned();
    let rocm_opt_dir = fx.rocm_opt_dir.to_string_lossy().into_owned();
    let override_path = fx.override_path.to_string_lossy().into_owned();

    let current_exe = installer_binary_path();
    let handle = spawn_privileged_phase(
        &current_exe,
        PrivilegedPhaseOptions { confirm_nvidia_driver_install: true, ..Default::default() },
        Some(&path),
        &[
            ("OS_RELEASE_FILE", &os_release),
            ("ROCM_OPT_DIR", &rocm_opt_dir),
            ("OLLAMA_SERVICE_OVERRIDE_PATH", &override_path),
        ],
    )
    .unwrap();

    let lines: Vec<String> = handle
        .lines
        .iter()
        .map(|line| match line {
            PhaseLine::Stdout(s) | PhaseLine::Stderr(s) => s,
        })
        .collect();
    let status = handle.wait();
    let pacman_calls = fs::read_to_string(&fx.pacman_log).unwrap_or_default();
    fs::remove_dir_all(&fx.tmp).ok();

    assert_eq!(status, Ok(()), "full log:\n{}", lines.join("\n"));

    // The whole point: a confirmed decision really reaches pacman, with
    // core::install::gpu::nvidia_plan's exact Arch package list.
    assert_eq!(pacman_calls.trim(), "-Sy --noconfirm --needed nvidia nvidia-utils");

    let joined = lines.join("\n");
    assert!(joined.contains(r#""id":"gpu","label":"Configuring GPU","status":"done""#), "{joined}");
    assert!(joined.contains("Nvidia driver install confirmed - proceeding."));
    assert!(joined.contains("Reboot the machine then re-run the installer"));
    assert!(!joined.contains("needsconfirmation"), "{joined}");
}
